from django.urls import path

from .views import (
    DirectMessageThreadView,
    FriendRequestAcceptView,
    FriendRequestCancelView,
    FriendRequestCreateView,
    FriendRequestDeclineView,
    FriendshipRemoveView,
    LoginView,
    LogoutView,
    MeView,
    NotificationPreferencesView,
    PushDeviceView,
    RegisterView,
    RoomInvitationAcceptView,
    RoomInvitationCreateView,
    RoomInvitationDeclineView,
    SocialBlockedUsersView,
    SocialBlockUserView,
    SocialHeartbeatView,
    SocialOnlineUsersView,
    SocialOverviewView,
    SocialUnblockUserView,
    SocialUserSearchView,
    StatisticsView,
)

urlpatterns = [
    path("auth/register/", RegisterView.as_view(), name="auth-register"),
    path("auth/login/", LoginView.as_view(), name="auth-login"),
    path("auth/me/", MeView.as_view(), name="auth-me"),
    path("auth/logout/", LogoutView.as_view(), name="auth-logout"),
    path("stats/", StatisticsView.as_view(), name="statistics"),
    path("social/heartbeat/", SocialHeartbeatView.as_view(), name="social-heartbeat"),
    path("social/overview/", SocialOverviewView.as_view(), name="social-overview"),
    path("social/online/", SocialOnlineUsersView.as_view(), name="social-online"),
    path("social/users/search/", SocialUserSearchView.as_view(), name="social-user-search"),
    path("social/blocked/", SocialBlockedUsersView.as_view(), name="social-blocked"),
    path("social/users/<int:user_id>/block/", SocialBlockUserView.as_view(), name="social-block-user"),
    path("social/users/<int:user_id>/unblock/", SocialUnblockUserView.as_view(), name="social-unblock-user"),
    path(
        "social/notifications/settings/",
        NotificationPreferencesView.as_view(),
        name="social-notification-settings",
    ),
    path(
        "social/notifications/devices/",
        PushDeviceView.as_view(),
        name="social-push-devices",
    ),
    path("social/friends/request/", FriendRequestCreateView.as_view(), name="friend-request"),
    path("social/friends/<int:pk>/accept/", FriendRequestAcceptView.as_view(), name="friend-accept"),
    path("social/friends/<int:pk>/decline/", FriendRequestDeclineView.as_view(), name="friend-decline"),
    path("social/friends/<int:pk>/cancel/", FriendRequestCancelView.as_view(), name="friend-cancel"),
    path("social/friends/<int:pk>/remove/", FriendshipRemoveView.as_view(), name="friend-remove"),
    path("social/chats/<int:user_id>/", DirectMessageThreadView.as_view(), name="direct-message-thread"),
    path("social/rooms/<int:room_id>/invitations/", RoomInvitationCreateView.as_view(), name="room-invitations"),
    path("social/invitations/<int:pk>/accept/", RoomInvitationAcceptView.as_view(), name="room-invitation-accept"),
    path("social/invitations/<int:pk>/decline/", RoomInvitationDeclineView.as_view(), name="room-invitation-decline"),
]
